// Database Seed Data
const seedListings = [
    // Different Electronics Listings
    {
        "listing_id": "",
        "user_id": 1,
        "title": "MacBook Pro 2019",
        "price": 1200.00,
        "description": "A 2019 MacBook Pro in excellent condition.",
        "status": "",
        "category_id": 2,
        "created_at": "",
        "is_trade": "",
        "image_paths": "",
        "listing_views": "",
        "featured": "",
        "condition": "new",
        "location": "Los Angeles, California"
    },
    {
        "listing_id": "",
        "user_id": 1,
        "title": "iPhone 12 Pro Max",
        "price": 1100.00,
        "description": "A brand new iPhone 12 Pro Max in the original packaging.",
        "status": "",
        "category_id": 2,
        "created_at": "",
        "is_trade": "",
        "image_paths": "",
        "listing_views": "",
        "featured": "",
        "condition": "new",
        "location": "Los Angeles, California"
    },
    {
        "listing_id": "",
        "user_id": 1,
        "title": "AirPods Pro",
        "price": 200.00,
        "description": "Brand new AirPods Pro in the original packaging.",
        "status": "",
        "category_id": 2,
        "created_at": "",
        "is_trade": "",
        "image_paths": "",
        "listing_views": "",
        "featured": "",
        "condition": "new",
        "location": "Los Angeles, California"
    },
    {
        "listing_id": "",
        "user_id": 1,
        "title": "iPad Pro 2020",
        "price": 800.00,
        "description": "A 2020 iPad Pro in excellent condition.",
        "status": "",
        "category_id": 2,
        "created_at": "",
        "is_trade": "",
        "image_paths": "",
        "listing_views": "",
        "featured": "",
        "condition": "new",
        "location": "Los Angeles, California"
    },
    {
        "listing_id": "",
        "user_id": 1,
        "title": "Apple Watch Series 6",
        "price": 400.00,
        "description": "Brand new Apple Watch Series 6 in the original packaging.",
        "status": "",
        "category_id": 2,
        "created_at": "",
        "is_trade": "",
        "image_paths": "",
        "listing_views": "",
        "featured": "",
        "condition": "new",
        "location": "Los Angeles, California"
    },
    // Different Furniture Listings
    {
        "listing_id": "",
        "user_id": 1,
        "title": "Sofa",
        "price": 300.00,
        "description": "A comfortable sofa in excellent condition.",
        "status": "",
        "category_id": 1,
        "created_at": "",
        "is_trade": "",
        "image_paths": "",
        "listing_views": "",
        "featured": "",
        "condition": "new",
        "location": "Los Angeles, California"
    },
    {
        "listing_id": "",
        "user_id": 1,
        "title": "Dining Table Set",
        "price": 250.00,
        "description": "A dining table set with 4 chairs in excellent condition.",
        "status": "",
        "category_id": 1,
        "created_at": "",
        "is_trade": "",
        "image_paths": "",
        "listing_views": "",
        "featured": "",
        "condition": "new",
        "location": "Los Angeles, California"
    },
    {
        "listing_id": "",
        "user_id": 1,
        "title": "Coffee Table",
        "price": 100.00,
        "description": "A coffee table in excellent condition.",
        "status": "",
        "category_id": 1,
        "created_at": "",
        "is_trade": "",
        "image_paths": "",
        "listing_views": "",
        "featured": "",
        "condition": "new",
        "location": "Los Angeles, California"
    },
    {
        "listing_id": "",
        "user_id": 1,
        "title": "Bookshelf",
        "price": 50.00,
        "description": "A bookshelf in excellent condition.",
        "status": "",
        "category_id": 1,
        "created_at": "",
        "is_trade": "",
        "image_paths": "",
        "listing_views": "",
        "featured": "",
        "condition": "new",
        "location": "Los Angeles, California"
    },
    // Different Clothing Listings
    {
        "listing_id": "",
        "user_id": 1,
        "title": "Shirt",
        "price": 20.00,
        "description": "A comfortable shirt in excellent condition.",
        "status": "",
        "category_id": 3,
        "created_at": "",
        "is_trade": "",
        "image_paths": "",
        "listing_views": "",
        "featured": "",
        "condition": "new",
        "location": "Los Angeles, California"
    },
    {
        "listing_id": "",
        "user_id": 1,
        "title": "Pants",
        "price": 30.00,
        "description": "A comfortable pair of pants in excellent condition.",
        "status": "",
        "category_id": 3,
        "created_at": "",
        "is_trade": "",
        "image_paths": "",
        "listing_views": "",
        "featured": "",
        "condition": "new",
        "location": "Los Angeles, California"
    },
    {
        "listing_id": "",
        "user_id": 1,
        "title": "Dress",
        "price": 50.00,
        "description": "A beautiful dress in excellent condition.",
        "status": "",
        "category_id": 3,
        "created_at": "",
        "is_trade": "",
        "image_paths": "",
        "listing_views": "",
        "featured": "",
        "condition": "new",
        "location": "Los Angeles, California"
    },
    {
        "listing_id": "",
        "user_id": 1,
        "title": "Jacket",
        "price": 60.00,
        "description": "A warm jacket in excellent condition.",
        "status": "",
        "category_id": 3,
        "created_at": "",
        "is_trade": "",
        "image_paths": "",
        "listing_views": "",
        "featured": "",
        "condition": "new",
        "location": "Los Angeles, California"
    },
    //Textbook Listings
    {
        "listing_id": "",
        "user_id": 1,
        "title": "Calculus Textbook",
        "price": 50.00,
        "description": "A calculus textbook in excellent condition.",
        "status": "",
        "category_id": 4,
        "created_at": "",
        "is_trade": "",
        "image_paths": "",
        "listing_views": "",
        "featured": "",
        "condition": "new",
        "location": "Los Angeles, California"
    },
    {
        "listing_id": "",
        "user_id": 1,
        "title": "Physics Textbook",
        "price": 60.00,
        "description": "A physics textbook in excellent condition.",
        "status": "",
        "category_id": 4,
        "created_at": "",
        "is_trade": "",
        "image_paths": "",
        "listing_views": "",
        "featured": "",
        "condition": "new",
        "location": "Los Angeles, California"
    },
    {
        "listing_id": "",
        "user_id": 1,
        "title": "Chemistry Textbook",
        "price": 70.00,
        "description": "A chemistry textbook in excellent condition.",
        "status": "",
        "category_id": 4,
        "created_at": "",
        "is_trade": "",
        "image_paths": "",
        "listing_views": "",
        "featured": "",
        "condition": "new",
        "location": "Los Angeles, California"
    },
    {
        "listing_id": "",
        "user_id": 1,
        "title": "Biology Textbook",
        "price": 80.00,
        "description": "A biology textbook in excellent condition.",
        "status": "",
        "category_id": 4,
        "created_at": "",
        "is_trade": "",
        "image_paths": "",
        "listing_views": "",
        "featured": "",
        "condition": "new",
        "location": "Los Angeles, California"
    },
    {
        "listing_id": "",
        "user_id": 1,
        "title": "Computer Science Textbook",
        "price": 90.00,
        "description": "A computer science textbook in excellent condition.",
        "status": "",
        "category_id": 4,
        "created_at": "",
        "is_trade": "",
        "image_paths": "",
        "listing_views": "",
        "featured": "",
        "condition": "new",
        "location": "Los Angeles, California"
    }
]


// INSERT INTO listings (
//     user_id, title, price, description, status, category_id, created_at, 
//     is_trade, image_paths, listing_views, featured, condition, location
// )
// VALUES
//     (1, 'MacBook Pro 2019', 1200.00, 'A 2019 MacBook Pro in excellent condition.', 'active', 2, CURRENT_TIMESTAMP, false, NULL, 0, 0, 'new', 'Los Angeles, California'),
//     (1, 'iPhone 12 Pro Max', 1100.00, 'A brand new iPhone 12 Pro Max in the original packaging.', 'active', 2, CURRENT_TIMESTAMP, false, NULL, 0, 0, 'new', 'Los Angeles, California'),
//     (1, 'AirPods Pro', 200.00, 'Brand new AirPods Pro in the original packaging.', 'active', 2, CURRENT_TIMESTAMP, false, NULL, 0, 0, 'new', 'Los Angeles, California'),
//     (1, 'iPad Pro 2020', 800.00, 'A 2020 iPad Pro in excellent condition.', 'active', 2, CURRENT_TIMESTAMP, false, NULL, 0, 0, 'new', 'Los Angeles, California'),
//     (1, 'Apple Watch Series 6', 400.00, 'Brand new Apple Watch Series 6 in the original packaging.', 'active', 2, CURRENT_TIMESTAMP, false, NULL, 0, 0, 'new', 'Los Angeles, California'),
//     (1, 'Sofa', 300.00, 'A comfortable sofa in excellent condition.', 'active', 1, CURRENT_TIMESTAMP, false, NULL, 0, 0, 'new', 'Los Angeles, California'),
//     (1, 'Dining Table Set', 250.00, 'A dining table set with 4 chairs in excellent condition.', 'active', 1, CURRENT_TIMESTAMP, false, NULL, 0, 0, 'new', 'Los Angeles, California'),
//     (1, 'Coffee Table', 100.00, 'A coffee table in excellent condition.', 'active', 1, CURRENT_TIMESTAMP, false, NULL, 0, 0, 'new', 'Los Angeles, California'),
//     (1, 'Bookshelf', 50.00, 'A bookshelf in excellent condition.', 'active', 1, CURRENT_TIMESTAMP, false, NULL, 0, 0, 'new', 'Los Angeles, California'),
//     (1, 'Shirt', 20.00, 'A comfortable shirt in excellent condition.', 'active', 3, CURRENT_TIMESTAMP, false, NULL, 0, 0, 'new', 'Los Angeles, California'),
//     (1, 'Pants', 30.00, 'A comfortable pair of pants in excellent condition.', 'active', 3, CURRENT_TIMESTAMP, false, NULL, 0, 0, 'new', 'Los Angeles, California'),
//     (1, 'Dress', 50.00, 'A beautiful dress in excellent condition.', 'active', 3, CURRENT_TIMESTAMP, false, NULL, 0, 0, 'new', 'Los Angeles, California'),
//     (1, 'Jacket', 60.00, 'A warm jacket in excellent condition.', 'active', 3, CURRENT_TIMESTAMP, false, NULL, 0, 0, 'new', 'Los Angeles, California'),
//     (1, 'Calculus Textbook', 50.00, 'A calculus textbook in excellent condition.', 'active', 4, CURRENT_TIMESTAMP, false, NULL, 0, 0, 'new', 'Los Angeles, California'),
//     (1, 'Physics Textbook', 60.00, 'A physics textbook in excellent condition.', 'active', 4, CURRENT_TIMESTAMP, false, NULL, 0, 0, 'new', 'Los Angeles, California'),
//     (1, 'Chemistry Textbook', 70.00, 'A chemistry textbook in excellent condition.', 'active', 4, CURRENT_TIMESTAMP, false, NULL, 0, 0, 'new', 'Los Angeles, California'),
//     (1, 'Biology Textbook', 80.00, 'A biology textbook in excellent condition.', 'active', 4, CURRENT_TIMESTAMP, false, NULL, 0, 0, 'new', 'Los Angeles, California'),
//     (1, 'Computer Science Textbook', 90.00, 'A computer science textbook in excellent condition.', 'active', 4, CURRENT_TIMESTAMP, false, NULL, 0, 0, 'new', 'Los Angeles, California');
